import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "./components/Navbar";
import Footer from "./components/Footer";
import Audio from "./components/audio";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Deesh Catering Services",
  description: "Generated by Egwu Marvin Epie",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        {/* <Audio/> */}
        <Navbar/>

        <div className="min-h-screen text-4xl">
        {children}
        </div>

        <Footer/>
        
        {/* <Audio/> */}
        </body>
    </html>
  );
}
